<?php

use yii\db\Schema;
use yii\db\Migration;

class m210615_093711_struktur_organisasiDataInsert extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->execute("set foreign_key_checks=0");
        $this->truncateTable('{{%struktur_organisasi}}');
        $this->batchInsert('{{%struktur_organisasi}}',
                           ["id", "parent_id", "tipe", "nama", "alias", "kode", "created_at", "updated_at", "created_by", "updated_by"],
                            [
    [
        'id' => '1',
        'parent_id' => null,
        'tipe' => 'GROUP',
        'nama' => 'TMS GROUP',
        'alias' => 'Induk Perusahaan',
        'kode' => 'TMS-GROUP',
        'created_at' => '1623664841',
        'updated_at' => '1623664841',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '2',
        'parent_id' => '1',
        'tipe' => 'PERUSAHAAN',
        'nama' => 'PT. Pelayaran Tresnamuda Sejati',
        'alias' => 'Tresnamuda',
        'kode' => 'TMS',
        'created_at' => '1623664999',
        'updated_at' => '1623665178',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '3',
        'parent_id' => '1',
        'tipe' => 'PERUSAHAAN',
        'nama' => 'PT. Jameson Freight Semesta',
        'alias' => 'Jameson',
        'kode' => 'JFS',
        'created_at' => '1623665100',
        'updated_at' => '1623665100',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '4',
        'parent_id' => '1',
        'tipe' => 'PERUSAHAAN',
        'nama' => 'PT. Tsurumaru Logistics Indonesia',
        'alias' => 'Tsurumaru',
        'kode' => 'TLI',
        'created_at' => '1623665293',
        'updated_at' => '1623665293',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '5',
        'parent_id' => '1',
        'tipe' => 'PERUSAHAAN',
        'nama' => 'PT. Nicholas Anwar Konsultan',
        'alias' => 'NAK',
        'kode' => 'NAK',
        'created_at' => '1623665327',
        'updated_at' => '1623665327',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '6',
        'parent_id' => '1',
        'tipe' => 'PERUSAHAAN',
        'nama' => 'PT. Samudera Daka Lines',
        'alias' => 'SDL',
        'kode' => 'SDL',
        'created_at' => '1623665354',
        'updated_at' => '1623665362',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '7',
        'parent_id' => '1',
        'tipe' => 'PERUSAHAAN',
        'nama' => 'PT. Tresna Portal Agensi',
        'alias' => 'TPA',
        'kode' => 'TPA',
        'created_at' => '1623665411',
        'updated_at' => '1623665411',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '8',
        'parent_id' => '1',
        'tipe' => 'PERUSAHAAN',
        'nama' => 'PT. Dynamic Container Lines',
        'alias' => 'DCL',
        'kode' => 'DCL',
        'created_at' => '1623665453',
        'updated_at' => '1623665453',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '9',
        'parent_id' => '1',
        'tipe' => 'PERUSAHAAN',
        'nama' => 'PT. Indo Formosa Trading',
        'alias' => 'Indoformosa',
        'kode' => 'IFT',
        'created_at' => '1623665478',
        'updated_at' => '1623665478',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '10',
        'parent_id' => '12',
        'tipe' => 'JABATAN',
        'nama' => 'Direktur Utama',
        'alias' => 'Dirut',
        'kode' => 'TMS_JKT_DIRUT',
        'created_at' => '1623728622',
        'updated_at' => '1623739671',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '11',
        'parent_id' => '10',
        'tipe' => 'JABATAN',
        'nama' => 'Manajer Penjamin Mutu & Keselamatan',
        'alias' => '',
        'kode' => 'TMS_JKT_MANAJER_MUTU',
        'created_at' => '1623728911',
        'updated_at' => '1623739695',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '12',
        'parent_id' => '2',
        'tipe' => 'CABANG',
        'nama' => 'TMS Jakarta',
        'alias' => 'Jakarta',
        'kode' => 'JKT',
        'created_at' => '1623729248',
        'updated_at' => '1623739073',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '13',
        'parent_id' => '11',
        'tipe' => 'JABATAN',
        'nama' => 'Kabag Penjamin Mutu & Keselamatan',
        'alias' => 'Kepala Bagian',
        'kode' => 'TMS_JKT_KABAG_MUTU',
        'created_at' => '1623732673',
        'updated_at' => '1623739728',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '14',
        'parent_id' => '2',
        'tipe' => 'CABANG',
        'nama' => 'Surabaya',
        'alias' => 'Surabaya',
        'kode' => 'TMS_SBY',
        'created_at' => '1623733936',
        'updated_at' => '1623739741',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '15',
        'parent_id' => '2',
        'tipe' => 'CABANG',
        'nama' => 'Semarang',
        'alias' => 'SMG',
        'kode' => 'SMG',
        'created_at' => '1623734560',
        'updated_at' => '1623734560',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '17',
        'parent_id' => '14',
        'tipe' => 'JABATAN',
        'nama' => 'Direktur Utama',
        'alias' => 'DIRUT',
        'kode' => 'TMS_SBY_DIRUT',
        'created_at' => '1623734845',
        'updated_at' => '1623739753',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '18',
        'parent_id' => '17',
        'tipe' => 'JABATAN',
        'nama' => 'Direktur Operasi & Komersial',
        'alias' => 'DIR-OPS-COM',
        'kode' => 'TMS_SBY_DIR_OPS_COM',
        'created_at' => '1623735287',
        'updated_at' => '1623739771',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '19',
        'parent_id' => '10',
        'tipe' => 'JABATAN',
        'nama' => 'Direktur Operasi & Kommersial',
        'alias' => 'Dirut Ops',
        'kode' => 'TMS_JKT_DIRUT_OPS_COM',
        'created_at' => '1623735355',
        'updated_at' => '1623739699',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '20',
        'parent_id' => '10',
        'tipe' => 'JABATAN',
        'nama' => 'Direktur Keuangan & Akunting',
        'alias' => 'DIR-FIN',
        'kode' => 'TMS_JKT_DIRUT_FIN',
        'created_at' => '1623735884',
        'updated_at' => '1623739705',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '23',
        'parent_id' => '20',
        'tipe' => 'JABATAN',
        'nama' => 'General Manajer Keuangan',
        'alias' => 'GM Finance',
        'kode' => 'TMS_JKT_GM_FIN',
        'created_at' => '1623737163',
        'updated_at' => '1623739709',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '24',
        'parent_id' => '20',
        'tipe' => 'JABATAN',
        'nama' => 'Manajer Akunting',
        'alias' => 'Manajer Akunting',
        'kode' => 'TMS_JKT_MANAJER_AKUNTING',
        'created_at' => '1623737201',
        'updated_at' => '1623739714',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '26',
        'parent_id' => '27',
        'tipe' => 'JABATAN',
        'nama' => 'General Manajer Marketing',
        'alias' => 'GM Marketing',
        'kode' => 'TMS_JKT_GM_MARKETING',
        'created_at' => '1623737501',
        'updated_at' => '1623742336',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '27',
        'parent_id' => '19',
        'tipe' => 'DEPARTEMEN',
        'nama' => 'Dept. Marketing',
        'alias' => 'MKT',
        'kode' => 'TMS_JKT_MKT',
        'created_at' => '1623742281',
        'updated_at' => '1623742427',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '28',
        'parent_id' => '19',
        'tipe' => 'DEPARTEMEN',
        'nama' => 'Dept. Operasi & EQC',
        'alias' => 'OPS',
        'kode' => 'TMS_JKT_OPS',
        'created_at' => '1623742397',
        'updated_at' => '1623742418',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '29',
        'parent_id' => '28',
        'tipe' => 'GROUP',
        'nama' => 'General Manajer Operasi & EQC',
        'alias' => 'GM OPS',
        'kode' => 'TMS_JKT_OPS_GM',
        'created_at' => '1623742486',
        'updated_at' => '1623742486',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '30',
        'parent_id' => '29',
        'tipe' => 'JABATAN',
        'nama' => 'Manajer EQC',
        'alias' => 'Manajer EQC',
        'kode' => 'TMS_JKT_OPS_MANAJER_EQC',
        'created_at' => '1623742557',
        'updated_at' => '1623742557',
        'created_by' => '1',
        'updated_by' => '1',
    ],
    [
        'id' => '31',
        'parent_id' => '29',
        'tipe' => 'JABATAN',
        'nama' => 'Manajer Operasi',
        'alias' => 'Manajer Operasi',
        'kode' => 'TMS_JKT_OPS_MANAJER',
        'created_at' => '1623742619',
        'updated_at' => '1623742619',
        'created_by' => '1',
        'updated_by' => '1',
    ],
]
        );
        $this->execute("set foreign_key_checks=1");
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%struktur_organisasi}} CASCADE');
    }
}
