<?php

use yii\db\Schema;
use yii\db\Migration;

class m210614_052753_auth_itemDataInsert extends Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init();
    }

    public function safeUp()
    {
        $this->execute("set foreign_key_checks=0");
        $this->truncateTable('{{%auth_item}}');
        $this->batchInsert('{{%auth_item}}',
                           ["name", "type", "description", "rule_name", "data", "created_at", "updated_at"],
                            [
    [
        'name' => '/*',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622267956',
        'updated_at' => '1622267956',
    ],
    [
        'name' => '/admin/assignment/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622267746',
        'updated_at' => '1622267746',
    ],
    [
        'name' => '/admin/menu/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622268266',
        'updated_at' => '1622268266',
    ],
    [
        'name' => '/admin/permission/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622268374',
        'updated_at' => '1622268374',
    ],
    [
        'name' => '/admin/role/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622268383',
        'updated_at' => '1622268383',
    ],
    [
        'name' => '/admin/route/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622268260',
        'updated_at' => '1622268260',
    ],
    [
        'name' => '/admin/rule/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622268393',
        'updated_at' => '1622268393',
    ],
    [
        'name' => '/admin/user/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622268406',
        'updated_at' => '1622268406',
    ],
    [
        'name' => '/agama/create',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407260',
        'updated_at' => '1623407260',
    ],
    [
        'name' => '/agama/delete',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407260',
        'updated_at' => '1623407260',
    ],
    [
        'name' => '/agama/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623386652',
        'updated_at' => '1623386652',
    ],
    [
        'name' => '/agama/update',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407260',
        'updated_at' => '1623407260',
    ],
    [
        'name' => '/agama/view',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407260',
        'updated_at' => '1623407260',
    ],
    [
        'name' => '/card-ajax/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622920162',
        'updated_at' => '1622920162',
    ],
    [
        'name' => '/card/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622731415',
        'updated_at' => '1622731415',
    ],
    [
        'name' => '/debug/*',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622559612',
        'updated_at' => '1622559612',
    ],
    [
        'name' => '/debug/default/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622571414',
        'updated_at' => '1622571414',
    ],
    [
        'name' => '/gii/*',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622289952',
        'updated_at' => '1622289952',
    ],
    [
        'name' => '/gii/default/*',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622559600',
        'updated_at' => '1622559600',
    ],
    [
        'name' => '/gii/default/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622559682',
        'updated_at' => '1622559682',
    ],
    [
        'name' => '/karyawan/create',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623402505',
        'updated_at' => '1623402505',
    ],
    [
        'name' => '/karyawan/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623386166',
        'updated_at' => '1623386166',
    ],
    [
        'name' => '/karyawan/update',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623402506',
        'updated_at' => '1623402506',
    ],
    [
        'name' => '/karyawan/view',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623402507',
        'updated_at' => '1623402507',
    ],
    [
        'name' => '/karyawan/view-update-delete',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623402741',
        'updated_at' => '1623402741',
    ],
    [
        'name' => '/mimin/role/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622778828',
        'updated_at' => '1622778828',
    ],
    [
        'name' => '/mimin/route/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622778833',
        'updated_at' => '1622778833',
    ],
    [
        'name' => '/mimin/user/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622778837',
        'updated_at' => '1622778837',
    ],
    [
        'name' => '/quotation-ajax/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622917957',
        'updated_at' => '1622917957',
    ],
    [
        'name' => '/quotation/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622792321',
        'updated_at' => '1622792321',
    ],
    [
        'name' => '/site/*',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623402467',
        'updated_at' => '1623402467',
    ],
    [
        'name' => '/site/about',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622267463',
        'updated_at' => '1622267463',
    ],
    [
        'name' => '/site/contact',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622267461',
        'updated_at' => '1622267461',
    ],
    [
        'name' => '/site/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622267453',
        'updated_at' => '1622267453',
    ],
    [
        'name' => '/site/login',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622267458',
        'updated_at' => '1622267458',
    ],
    [
        'name' => '/site/logout',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622267467',
        'updated_at' => '1622267467',
    ],
    [
        'name' => '/status-perkawinan/create',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407266',
        'updated_at' => '1623407266',
    ],
    [
        'name' => '/status-perkawinan/delete',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407266',
        'updated_at' => '1623407266',
    ],
    [
        'name' => '/status-perkawinan/index',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623386658',
        'updated_at' => '1623386658',
    ],
    [
        'name' => '/status-perkawinan/update',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407266',
        'updated_at' => '1623407266',
    ],
    [
        'name' => '/status-perkawinan/view',
        'type' => '2',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407266',
        'updated_at' => '1623407266',
    ],
    [
        'name' => 'manager',
        'type' => '1',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623407241',
        'updated_at' => '1623407241',
    ],
    [
        'name' => 'super-admin',
        'type' => '1',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1622267920',
        'updated_at' => '1622810832',
    ],
    [
        'name' => 'user-default',
        'type' => '1',
        'description' => null,
        'rule_name' => null,
        'data' => null,
        'created_at' => '1623402454',
        'updated_at' => '1623402454',
    ],
]
        );

        $this->execute("set foreign_key_checks=1");
    }

    public function safeDown()
    {
        //$this->truncateTable('{{%auth_item}} CASCADE');
    }
}
