<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "alamat_karyawan".
 *
 * @property integer $id
 * @property integer $karyawan_id
 * @property string $type
 * @property string $atas_nama
 * @property string $jalan
 * @property string $block
 * @property string $nomor
 * @property string $rt
 * @property string $rw
 * @property string $kecamatan
 * @property string $kelurahan
 * @property string $kabupaten
 * @property string $propinsi
 * @property string $kode_pos
 * @property string $nomor_telepon
 * @property string $email
 * @property string $keterangan
 *
 * @property \app\models\Karyawan $karyawan
 * @property string $aliasModel
 */
abstract class AlamatKaryawan extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const TYPE_SESUAI_KTP = 'Sesuai KTP';
    const TYPE_DOMISILI_SEKARANG = 'Domisili Sekarang';
    const TYPE_PELAPORAN_PAJAK = 'Pelaporan Pajak';
    const TYPE_KERABAT_YANG_BISA_DIHUBUNGI = 'Kerabat Yang Bisa Dihubungi';
    const TYPE_LAINNYA = 'Lainnya';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'alamat_karyawan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['karyawan_id'], 'integer'],
            [['type', 'atas_nama', 'jalan'], 'required'],
            [['type', 'jalan', 'keterangan'], 'string'],
            [['atas_nama', 'block', 'nomor', 'kecamatan', 'kelurahan', 'kabupaten', 'propinsi', 'kode_pos', 'nomor_telepon', 'email'], 'string', 'max' => 255],
            [['rt', 'rw'], 'string', 'max' => 50],
            [['karyawan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Karyawan::className(), 'targetAttribute' => ['karyawan_id' => 'id']],
            ['type', 'in', 'range' => [
                    self::TYPE_SESUAI_KTP,
                    self::TYPE_DOMISILI_SEKARANG,
                    self::TYPE_PELAPORAN_PAJAK,
                    self::TYPE_KERABAT_YANG_BISA_DIHUBUNGI,
                    self::TYPE_LAINNYA,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'karyawan_id' => 'Karyawan ID',
            'type' => 'Type',
            'atas_nama' => 'Atas Nama',
            'jalan' => 'Jalan',
            'block' => 'Block',
            'nomor' => 'Nomor',
            'rt' => 'Rt',
            'rw' => 'Rw',
            'kecamatan' => 'Kecamatan',
            'kelurahan' => 'Kelurahan',
            'kabupaten' => 'Kabupaten',
            'propinsi' => 'Propinsi',
            'kode_pos' => 'Kode Pos',
            'nomor_telepon' => 'Nomor Telepon',
            'email' => 'Email',
            'keterangan' => 'Keterangan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKaryawan()
    {
        return $this->hasOne(\app\models\Karyawan::className(), ['id' => 'karyawan_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\AlamatKaryawanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\AlamatKaryawanQuery(get_called_class());
    }


    /**
     * get column type enum value label
     * @param string $value
     * @return string
     */
    public static function getTypeValueLabel($value){
        $labels = self::optsType();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column type ENUM value labels
     * @return array
     */
    public static function optsType()
    {
        return [
            self::TYPE_SESUAI_KTP => 'Sesuai Ktp',
            self::TYPE_DOMISILI_SEKARANG => 'Domisili Sekarang',
            self::TYPE_PELAPORAN_PAJAK => 'Pelaporan Pajak',
            self::TYPE_KERABAT_YANG_BISA_DIHUBUNGI => 'Kerabat Yang Bisa Dihubungi',
            self::TYPE_LAINNYA => 'Lainnya',
        ];
    }

}
