<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "aturan_uang_kehadiran".
 *
 * @property integer $id
 * @property string $nama
 * @property string $keterangan
 * @property integer $is_dapat_uang_kehadiran
 * @property integer $is_aktif
 * @property string $aliasModel
 */
abstract class AturanUangKehadiran extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'aturan_uang_kehadiran';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['keterangan'], 'string'],
            [['is_dapat_uang_kehadiran', 'is_aktif'], 'integer'],
            [['nama'], 'string', 'max' => 255],
            [['nama'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'keterangan' => 'Keterangan',
            'is_dapat_uang_kehadiran' => 'Is Dapat Uang Kehadiran',
            'is_aktif' => 'Is Aktif',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\AturanUangKehadiranQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\AturanUangKehadiranQuery(get_called_class());
    }


}
