<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "batal_ptkp".
 *
 * @property integer $id
 * @property string $nama
 * @property string $kode
 *
 * @property \app\models\KaryawanPtkp[] $karyawanPtkps
 * @property string $aliasModel
 */
abstract class BatalPtkp extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'batal_ptkp';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'kode'], 'required'],
            [['nama'], 'string', 'max' => 255],
            [['kode'], 'string', 'max' => 50],
            [['kode'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'kode' => 'Kode',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKaryawanPtkps()
    {
        return $this->hasMany(\app\models\KaryawanPtkp::className(), ['batal_ptkp_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\BatalPtkpQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\BatalPtkpQuery(get_called_class());
    }


}
