<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "form_perubahan_data_karyawan".
 *
 * @property integer $id
 * @property string $nomor_referensi
 * @property string $judul
 * @property string $deskripsi_umum
 * @property string $status
 * @property string $aksi_yang_dilakukan
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\FormPerubahanDataKaryawanDetail[] $formPerubahanDataKaryawanDetails
 * @property string $aliasModel
 */
abstract class FormPerubahanDataKaryawan extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_PENDING = 'PENDING';
    const STATUS_SEDANG_DIKERJAKAN = 'SEDANG DIKERJAKAN';
    const STATUS_SELESAI = 'SELESAI';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'form_perubahan_data_karyawan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul', 'deskripsi_umum'], 'required'],
            [['deskripsi_umum', 'status', 'aksi_yang_dilakukan'], 'string'],
            [['nomor_referensi', 'judul'], 'string', 'max' => 255],
            ['status', 'in', 'range' => [
                    self::STATUS_PENDING,
                    self::STATUS_SEDANG_DIKERJAKAN,
                    self::STATUS_SELESAI,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nomor_referensi' => 'Nomor Referensi',
            'judul' => 'Judul',
            'deskripsi_umum' => 'Deskripsi Umum',
            'status' => 'Status',
            'aksi_yang_dilakukan' => 'Aksi Yang Dilakukan',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFormPerubahanDataKaryawanDetails()
    {
        return $this->hasMany(\app\models\FormPerubahanDataKaryawanDetail::className(), ['form_perubahan_data_karyawan_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\FormPerubahanDataKaryawanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\FormPerubahanDataKaryawanQuery(get_called_class());
    }


    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_PENDING => 'Pending',
            self::STATUS_SEDANG_DIKERJAKAN => 'Sedang Dikerjakan',
            self::STATUS_SELESAI => 'Selesai',
        ];
    }

}
