<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "form_perubahan_data_karyawan_detail".
 *
 * @property integer $id
 * @property integer $form_perubahan_data_karyawan_id
 * @property string $nama_data
 * @property string $nilai_lama
 * @property string $nilai_baru
 * @property string $aksi
 * @property string $keterangan
 *
 * @property \app\models\FormPerubahanDataKaryawan $formPerubahanDataKaryawan
 * @property string $aliasModel
 */
abstract class FormPerubahanDataKaryawanDetail extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const AKSI_TAMBAH = 'Tambah';
    const AKSI_PERBARUI = 'Perbarui';
    const AKSI_HAPUS = 'Hapus';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'form_perubahan_data_karyawan_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['form_perubahan_data_karyawan_id'], 'integer'],
            [['nama_data', 'nilai_lama', 'nilai_baru'], 'required'],
            [['aksi', 'keterangan'], 'string'],
            [['nama_data', 'nilai_lama', 'nilai_baru'], 'string', 'max' => 255],
            [['form_perubahan_data_karyawan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\FormPerubahanDataKaryawan::className(), 'targetAttribute' => ['form_perubahan_data_karyawan_id' => 'id']],
            ['aksi', 'in', 'range' => [
                    self::AKSI_TAMBAH,
                    self::AKSI_PERBARUI,
                    self::AKSI_HAPUS,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'form_perubahan_data_karyawan_id' => 'Form Perubahan Data Karyawan ID',
            'nama_data' => 'Nama Data',
            'nilai_lama' => 'Nilai Lama',
            'nilai_baru' => 'Nilai Baru',
            'aksi' => 'Aksi',
            'keterangan' => 'Keterangan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFormPerubahanDataKaryawan()
    {
        return $this->hasOne(\app\models\FormPerubahanDataKaryawan::className(), ['id' => 'form_perubahan_data_karyawan_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\FormPerubahanDataKaryawanDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\FormPerubahanDataKaryawanDetailQuery(get_called_class());
    }


    /**
     * get column aksi enum value label
     * @param string $value
     * @return string
     */
    public static function getAksiValueLabel($value){
        $labels = self::optsAksi();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column aksi ENUM value labels
     * @return array
     */
    public static function optsAksi()
    {
        return [
            self::AKSI_TAMBAH => 'Tambah',
            self::AKSI_PERBARUI => 'Perbarui',
            self::AKSI_HAPUS => 'Hapus',
        ];
    }

}
