<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "jadwal_kerja".
 *
 * @property integer $id
 * @property string $nama
 * @property string $kode
 * @property string $keterangan
 * @property string $mulai_tanggal
 * @property string $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\JadwalKerjaDetail[] $jadwalKerjaDetails
 * @property string $aliasModel
 */
abstract class JadwalKerja extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_AKTIF = 'Aktif';
    const STATUS_TIDAK_AKTIF = 'Tidak Aktif';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jadwal_kerja';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'kode', 'mulai_tanggal'], 'required'],
            [['keterangan', 'status'], 'string'],
            [['mulai_tanggal'], 'safe'],
            [['nama', 'kode'], 'string', 'max' => 255],
            [['nama'], 'unique'],
            [['kode'], 'unique'],
            ['status', 'in', 'range' => [
                    self::STATUS_AKTIF,
                    self::STATUS_TIDAK_AKTIF,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'kode' => 'Kode',
            'keterangan' => 'Keterangan',
            'mulai_tanggal' => 'Mulai Tanggal',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJadwalKerjaDetails()
    {
        return $this->hasMany(\app\models\JadwalKerjaDetail::className(), ['jadwal_kerja_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\JadwalKerjaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\JadwalKerjaQuery(get_called_class());
    }


    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_AKTIF => 'Aktif',
            self::STATUS_TIDAK_AKTIF => 'Tidak Aktif',
        ];
    }

}
