<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "jadwal_kerja_detail_detail".
 *
 * @property integer $id
 * @property integer $jadwal_kerja_detail_id
 * @property integer $jam_kerja_id
 *
 * @property \app\models\JadwalKerjaDetail $jadwalKerjaDetail
 * @property \app\models\JamKerja $jamKerja
 * @property string $aliasModel
 */
abstract class JadwalKerjaDetailDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jadwal_kerja_detail_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['jadwal_kerja_detail_id', 'jam_kerja_id'], 'integer'],
            [['jadwal_kerja_detail_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JadwalKerjaDetail::className(), 'targetAttribute' => ['jadwal_kerja_detail_id' => 'id']],
            [['jam_kerja_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JamKerja::className(), 'targetAttribute' => ['jam_kerja_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'jadwal_kerja_detail_id' => 'Jadwal Kerja Detail ID',
            'jam_kerja_id' => 'Jam Kerja ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJadwalKerjaDetail()
    {
        return $this->hasOne(\app\models\JadwalKerjaDetail::className(), ['id' => 'jadwal_kerja_detail_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJamKerja()
    {
        return $this->hasOne(\app\models\JamKerja::className(), ['id' => 'jam_kerja_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\JadwalKerjaDetailDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\JadwalKerjaDetailDetailQuery(get_called_class());
    }


}
