<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "jam_kerja".
 *
 * @property integer $id
 * @property string $nama
 * @property string $kode
 * @property string $jam_masuk
 * @property string $jam_mulai_istrahat
 * @property string $jam_selesai_istrahat
 * @property string $jam_pulang
 * @property string $durasi
 * @property integer $dihitung
 * @property integer $toleransi_terlambat
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\JadwalKerjaDetailDetail[] $jadwalKerjaDetailDetails
 * @property string $aliasModel
 */
abstract class JamKerja extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const DURASI_DURASI_EFEKTIF = 'durasi_efektif';
    const DURASI_DURASI_AKTUAL = 'durasi_aktual';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jam_kerja';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'kode', 'jam_masuk', 'jam_pulang'], 'required'],
            [['jam_masuk', 'jam_mulai_istrahat', 'jam_selesai_istrahat', 'jam_pulang'], 'safe'],
            [['durasi'], 'string'],
            [['dihitung', 'toleransi_terlambat'], 'integer'],
            [['nama'], 'string', 'max' => 255],
            [['kode'], 'string', 'max' => 50],
            [['nama'], 'unique'],
            [['kode'], 'unique'],
            ['durasi', 'in', 'range' => [
                    self::DURASI_DURASI_EFEKTIF,
                    self::DURASI_DURASI_AKTUAL,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'kode' => 'Kode',
            'jam_masuk' => 'Jam Masuk',
            'jam_mulai_istrahat' => 'Jam Mulai Istrahat',
            'jam_selesai_istrahat' => 'Jam Selesai Istrahat',
            'jam_pulang' => 'Jam Pulang',
            'durasi' => 'Durasi',
            'dihitung' => 'Dihitung',
            'toleransi_terlambat' => 'Toleransi Terlambat',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'jam_masuk' => 'Masuk',
            'jam_mulai_istrahat' => 'Ist. Keluar',
            'jam_selesai_istrahat' => 'Ist. Kembali',
            'jam_pulang' => 'Pulang',
            'durasi' => 'Durasi Efektif adalah durasi kerja yang dihitung berdasarkan jam kerja pegawai, Durasi Aktual adalah durasi kerja yang dihitung berdasarkan scan kerja pegawai',
            'dihitung' => 'Satuan hari',
            'toleransi_terlambat' => 'Satuan Menit',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJadwalKerjaDetailDetails()
    {
        return $this->hasMany(\app\models\JadwalKerjaDetailDetail::className(), ['jam_kerja_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\JamKerjaQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\JamKerjaQuery(get_called_class());
    }


    /**
     * get column durasi enum value label
     * @param string $value
     * @return string
     */
    public static function getDurasiValueLabel($value){
        $labels = self::optsDurasi();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column durasi ENUM value labels
     * @return array
     */
    public static function optsDurasi()
    {
        return [
            self::DURASI_DURASI_EFEKTIF => 'Durasi Efektif',
            self::DURASI_DURASI_AKTUAL => 'Durasi Aktual',
        ];
    }

}
