<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "jenis_izin".
 *
 * @property integer $id
 * @property integer $kategori_izin_id
 * @property string $nama
 *
 * @property \app\models\KategoriIzin $kategoriIzin
 * @property \app\models\KehadiranDiInternalSistem[] $kehadiranDiInternalSistems
 * @property string $aliasModel
 */
abstract class JenisIzin extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'jenis_izin';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kategori_izin_id'], 'integer'],
            [['nama'], 'required'],
            [['nama'], 'string', 'max' => 255],
            [['kategori_izin_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\KategoriIzin::className(), 'targetAttribute' => ['kategori_izin_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kategori_izin_id' => 'Kategori Izin ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKategoriIzin()
    {
        return $this->hasOne(\app\models\KategoriIzin::className(), ['id' => 'kategori_izin_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKehadiranDiInternalSistems()
    {
        return $this->hasMany(\app\models\KehadiranDiInternalSistem::className(), ['jenis_izin_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\JenisIzinQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\JenisIzinQuery(get_called_class());
    }


}
