<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "karyawan_struktur_organisasi".
 *
 * @property integer $id
 * @property integer $karyawan_id
 * @property integer $struktur_organisasi_id
 * @property string $nomor_surat_pengangkatan
 * @property string $tanggal_aktif
 * @property string $tanggal_berakhir
 * @property string $alasan_berakhir
 *
 * @property \app\models\Karyawan $karyawan
 * @property \app\models\StrukturOrganisasi $strukturOrganisasi
 * @property string $aliasModel
 */
abstract class KaryawanStrukturOrganisasi extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'karyawan_struktur_organisasi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['karyawan_id', 'struktur_organisasi_id', 'nomor_surat_pengangkatan', 'tanggal_aktif'], 'required'],
            [['karyawan_id', 'struktur_organisasi_id'], 'integer'],
            [['tanggal_aktif', 'tanggal_berakhir'], 'safe'],
            [['nomor_surat_pengangkatan', 'alasan_berakhir'], 'string', 'max' => 255],
            [['karyawan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Karyawan::className(), 'targetAttribute' => ['karyawan_id' => 'id']],
            [['struktur_organisasi_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StrukturOrganisasi::className(), 'targetAttribute' => ['struktur_organisasi_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'karyawan_id' => 'Karyawan ID',
            'struktur_organisasi_id' => 'Struktur Organisasi ID',
            'nomor_surat_pengangkatan' => 'Nomor Surat Pengangkatan',
            'tanggal_aktif' => 'Tanggal Aktif',
            'tanggal_berakhir' => 'Tanggal Berakhir',
            'alasan_berakhir' => 'Alasan Berakhir',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKaryawan()
    {
        return $this->hasOne(\app\models\Karyawan::className(), ['id' => 'karyawan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStrukturOrganisasi()
    {
        return $this->hasOne(\app\models\StrukturOrganisasi::className(), ['id' => 'struktur_organisasi_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\KaryawanStrukturOrganisasiQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\KaryawanStrukturOrganisasiQuery(get_called_class());
    }


}
