<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "karyawan".
 *
 * @property integer $id
 * @property string $nomor_induk_karyawan
 * @property string $nama
 * @property string $nama_panggilan
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property string $status_kewarganegaraan
 * @property string $nomor_kartu_tanda_penduduk
 * @property string $nomor_kartu_keluarga
 * @property string $nomor_pokok_wajib_pajak
 * @property string $nomor_kitas_atau_sejenisnya
 * @property string $jenis_kelamin
 * @property integer $agama_id
 * @property integer $status_perkawinan_id
 * @property string $nama_ayah
 * @property string $nama_ibu
 * @property string $pendidikan_terakhir
 * @property string $tanggal_mulai_bekerja
 * @property string $tanggal_berhenti_bekerja
 * @property integer $alasan_berhenti_bekerja
 * @property integer $jadwal_kerja_id
 * @property string $mesin_absensi_password
 * @property string $mesin_absensi_rfid
 * @property string $mesin_absensi_previlege
 * @property string $mesin_absensi_telapak_tangan
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\KehadiranDiMesinAbsensi[] $absensis
 * @property \app\models\AlamatKaryawan[] $alamatKaryawans
 * @property \app\models\Agama $agama
 * @property \app\models\JadwalKerja $jadwalKerja
 * @property \app\models\StatusPerkawinan $statusPerkawinan
 * @property \app\models\KaryawanPtkp[] $karyawanPtkps
 * @property \app\models\KaryawanStrukturOrganisasi[] $karyawanStrukturOrganisasis
 * @property string $aliasModel
 */
abstract class Karyawan extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_KEWARGANEGARAAN_WNI = 'WNI';
    const STATUS_KEWARGANEGARAAN_WNA = 'WNA';
    const JENIS_KELAMIN_LAKI___LAKI = 'Laki - Laki';
    const JENIS_KELAMIN_PEREMPUAN = 'Perempuan';
    const PENDIDIKAN_TERAKHIR_SD = 'SD';
    const PENDIDIKAN_TERAKHIR_SMP = 'SMP';
    const PENDIDIKAN_TERAKHIR_SMA = 'SMA';
    const PENDIDIKAN_TERAKHIR_S1 = 'S1';
    const PENDIDIKAN_TERAKHIR_S2 = 'S2';
    const PENDIDIKAN_TERAKHIR_S3 = 'S3';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'karyawan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'jenis_kelamin', 'agama_id', 'status_perkawinan_id', 'pendidikan_terakhir', 'jadwal_kerja_id'], 'required'],
            [['tanggal_lahir', 'tanggal_mulai_bekerja', 'tanggal_berhenti_bekerja'], 'safe'],
            [['status_kewarganegaraan', 'jenis_kelamin', 'pendidikan_terakhir'], 'string'],
            [['agama_id', 'status_perkawinan_id', 'alasan_berhenti_bekerja', 'jadwal_kerja_id'], 'integer'],
            [['nomor_induk_karyawan', 'nama', 'nama_panggilan', 'tempat_lahir', 'nomor_kartu_tanda_penduduk', 'nomor_kartu_keluarga', 'nomor_pokok_wajib_pajak', 'nomor_kitas_atau_sejenisnya', 'nama_ayah', 'nama_ibu', 'mesin_absensi_password', 'mesin_absensi_rfid', 'mesin_absensi_previlege', 'mesin_absensi_telapak_tangan'], 'string', 'max' => 255],
            [['agama_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Agama::className(), 'targetAttribute' => ['agama_id' => 'id']],
            [['jadwal_kerja_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\JadwalKerja::className(), 'targetAttribute' => ['jadwal_kerja_id' => 'id']],
            [['status_perkawinan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StatusPerkawinan::className(), 'targetAttribute' => ['status_perkawinan_id' => 'id']],
            ['status_kewarganegaraan', 'in', 'range' => [
                    self::STATUS_KEWARGANEGARAAN_WNI,
                    self::STATUS_KEWARGANEGARAAN_WNA,
                ]
            ],
            ['jenis_kelamin', 'in', 'range' => [
                    self::JENIS_KELAMIN_LAKI___LAKI,
                    self::JENIS_KELAMIN_PEREMPUAN,
                ]
            ],
            ['pendidikan_terakhir', 'in', 'range' => [
                    self::PENDIDIKAN_TERAKHIR_SD,
                    self::PENDIDIKAN_TERAKHIR_SMP,
                    self::PENDIDIKAN_TERAKHIR_SMA,
                    self::PENDIDIKAN_TERAKHIR_S1,
                    self::PENDIDIKAN_TERAKHIR_S2,
                    self::PENDIDIKAN_TERAKHIR_S3,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nomor_induk_karyawan' => 'Nomor Induk Karyawan',
            'nama' => 'Nama',
            'nama_panggilan' => 'Nama Panggilan',
            'tempat_lahir' => 'Tempat Lahir',
            'tanggal_lahir' => 'Tanggal Lahir',
            'status_kewarganegaraan' => 'Status Kewarganegaraan',
            'nomor_kartu_tanda_penduduk' => 'Nomor Kartu Tanda Penduduk',
            'nomor_kartu_keluarga' => 'Nomor Kartu Keluarga',
            'nomor_pokok_wajib_pajak' => 'Nomor Pokok Wajib Pajak',
            'nomor_kitas_atau_sejenisnya' => 'Nomor Kitas Atau Sejenisnya',
            'jenis_kelamin' => 'Jenis Kelamin',
            'agama_id' => 'Agama ID',
            'status_perkawinan_id' => 'Status Perkawinan ID',
            'nama_ayah' => 'Nama Ayah',
            'nama_ibu' => 'Nama Ibu',
            'pendidikan_terakhir' => 'Pendidikan Terakhir',
            'tanggal_mulai_bekerja' => 'Tanggal Mulai Bekerja',
            'tanggal_berhenti_bekerja' => 'Tanggal Berhenti Bekerja',
            'alasan_berhenti_bekerja' => 'Alasan Berhenti Bekerja',
            'jadwal_kerja_id' => 'Jadwal Kerja ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'mesin_absensi_password' => 'Mesin KehadiranDiMesinAbsensi Password',
            'mesin_absensi_rfid' => 'Mesin KehadiranDiMesinAbsensi Rfid',
            'mesin_absensi_previlege' => 'Mesin KehadiranDiMesinAbsensi Previlege',
            'mesin_absensi_telapak_tangan' => 'Mesin KehadiranDiMesinAbsensi Telapak Tangan',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAbsensis()
    {
        return $this->hasMany(\app\models\KehadiranDiMesinAbsensi::className(), ['karyawan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlamatKaryawans()
    {
        return $this->hasMany(\app\models\AlamatKaryawan::className(), ['karyawan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAgama()
    {
        return $this->hasOne(\app\models\Agama::className(), ['id' => 'agama_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJadwalKerja()
    {
        return $this->hasOne(\app\models\JadwalKerja::className(), ['id' => 'jadwal_kerja_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatusPerkawinan()
    {
        return $this->hasOne(\app\models\StatusPerkawinan::className(), ['id' => 'status_perkawinan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKaryawanPtkps()
    {
        return $this->hasMany(\app\models\KaryawanPtkp::className(), ['karyawan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKaryawanStrukturOrganisasis()
    {
        return $this->hasMany(\app\models\KaryawanStrukturOrganisasi::className(), ['karyawan_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\KaryawanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\KaryawanQuery(get_called_class());
    }


    /**
     * get column status_kewarganegaraan enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusKewarganegaraanValueLabel($value){
        $labels = self::optsStatusKewarganegaraan();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status_kewarganegaraan ENUM value labels
     * @return array
     */
    public static function optsStatusKewarganegaraan()
    {
        return [
            self::STATUS_KEWARGANEGARAAN_WNI => 'Wni',
            self::STATUS_KEWARGANEGARAAN_WNA => 'Wna',
        ];
    }

    /**
     * get column jenis_kelamin enum value label
     * @param string $value
     * @return string
     */
    public static function getJenisKelaminValueLabel($value){
        $labels = self::optsJenisKelamin();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column jenis_kelamin ENUM value labels
     * @return array
     */
    public static function optsJenisKelamin()
    {
        return [
            self::JENIS_KELAMIN_LAKI___LAKI => 'Laki Laki',
            self::JENIS_KELAMIN_PEREMPUAN => 'Perempuan',
        ];
    }

    /**
     * get column pendidikan_terakhir enum value label
     * @param string $value
     * @return string
     */
    public static function getPendidikanTerakhirValueLabel($value){
        $labels = self::optsPendidikanTerakhir();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column pendidikan_terakhir ENUM value labels
     * @return array
     */
    public static function optsPendidikanTerakhir()
    {
        return [
            self::PENDIDIKAN_TERAKHIR_SD => 'Sd',
            self::PENDIDIKAN_TERAKHIR_SMP => 'Smp',
            self::PENDIDIKAN_TERAKHIR_SMA => 'Sma',
            self::PENDIDIKAN_TERAKHIR_S1 => 'S1',
            self::PENDIDIKAN_TERAKHIR_S2 => 'S2',
            self::PENDIDIKAN_TERAKHIR_S3 => 'S3',
        ];
    }

}
