<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "karyawan_struktur_organisasi".
 *
 * @property integer $id
 * @property integer $karyawan_id
 * @property integer $struktur_organisasi_id
 * @property string $jenis_jabatan
 * @property string $nomor_surat_pengangkatan
 * @property string $tanggal_aktif
 * @property string $tanggal_berakhir
 * @property string $alasan_berakhir
 *
 * @property \app\models\Karyawan $karyawan
 * @property \app\models\StrukturOrganisasi $strukturOrganisasi
 * @property string $aliasModel
 */
abstract class KaryawanStrukturOrganisasi extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const JENIS_JABATAN_UTAMA = 'Utama';
    const JENIS_JABATAN_PEJABAT_SEMENTARA = 'Pejabat Sementara';
    const JENIS_JABATAN_DI_PERBANTUKAN = 'Di-perbantukan';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'karyawan_struktur_organisasi';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['karyawan_id', 'struktur_organisasi_id'], 'integer'],
            [['struktur_organisasi_id'], 'required'],
            [['jenis_jabatan'], 'string'],
            [['tanggal_aktif', 'tanggal_berakhir'], 'safe'],
            [['nomor_surat_pengangkatan', 'alasan_berakhir'], 'string', 'max' => 255],
            [['karyawan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Karyawan::className(), 'targetAttribute' => ['karyawan_id' => 'id']],
            [['struktur_organisasi_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StrukturOrganisasi::className(), 'targetAttribute' => ['struktur_organisasi_id' => 'id']],
            ['jenis_jabatan', 'in', 'range' => [
                    self::JENIS_JABATAN_UTAMA,
                    self::JENIS_JABATAN_PEJABAT_SEMENTARA,
                    self::JENIS_JABATAN_DI_PERBANTUKAN,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'karyawan_id' => 'Karyawan ID',
            'struktur_organisasi_id' => 'Struktur Organisasi ID',
            'jenis_jabatan' => 'Jenis Jabatan',
            'nomor_surat_pengangkatan' => 'Nomor Surat Pengangkatan',
            'tanggal_aktif' => 'Tanggal Aktif',
            'tanggal_berakhir' => 'Tanggal Berakhir',
            'alasan_berakhir' => 'Alasan Berakhir',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKaryawan()
    {
        return $this->hasOne(\app\models\Karyawan::className(), ['id' => 'karyawan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStrukturOrganisasi()
    {
        return $this->hasOne(\app\models\StrukturOrganisasi::className(), ['id' => 'struktur_organisasi_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\KaryawanStrukturOrganisasiQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\KaryawanStrukturOrganisasiQuery(get_called_class());
    }


    /**
     * get column jenis_jabatan enum value label
     * @param string $value
     * @return string
     */
    public static function getJenisJabatanValueLabel($value){
        $labels = self::optsJenisJabatan();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column jenis_jabatan ENUM value labels
     * @return array
     */
    public static function optsJenisJabatan()
    {
        return [
            self::JENIS_JABATAN_UTAMA => 'Utama',
            self::JENIS_JABATAN_PEJABAT_SEMENTARA => 'Pejabat Sementara',
            self::JENIS_JABATAN_DI_PERBANTUKAN => 'Di Perbantukan',
        ];
    }

}
