<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "kategori_izin".
 *
 * @property integer $id
 * @property string $nama
 *
 * @property \app\models\JenisIzin[] $jenisIzins
 * @property string $aliasModel
 */
abstract class KategoriIzin extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'kategori_izin';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['nama'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisIzins()
    {
        return $this->hasMany(\app\models\JenisIzin::className(), ['kategori_izin_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\KategoriIzinQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\KategoriIzinQuery(get_called_class());
    }


}
