<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "libur".
 *
 * @property integer $id
 * @property string $tanggal
 * @property string $keterangan
 * @property string $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 * @property string $aliasModel
 */
abstract class Libur extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_HARI_LIBUR = 'Hari Libur';
    const STATUS_CUTI_BERSAMA = 'Cuti Bersama';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'libur';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tanggal', 'keterangan'], 'required'],
            [['tanggal'], 'safe'],
            [['keterangan', 'status'], 'string'],
            ['status', 'in', 'range' => [
                    self::STATUS_HARI_LIBUR,
                    self::STATUS_CUTI_BERSAMA,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tanggal' => 'Tanggal',
            'keterangan' => 'Keterangan',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\LiburQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\LiburQuery(get_called_class());
    }


    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_HARI_LIBUR => 'Hari Libur',
            self::STATUS_CUTI_BERSAMA => 'Cuti Bersama',
        ];
    }

}
