<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "quotation".
 *
 * @property integer $id
 * @property integer $card_pic_and_address_id
 * @property integer $goods_type_id
 * @property string $issue_date
 * @property string $reference_number
 * @property string $status
 * @property string $remarks
 * @property string $validity
 * @property array $log
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\QuotationJob[] $quotationJobs
 * @property string $aliasModel
 */
abstract class Quotation extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_DRAFT = 'Draft';
    const STATUS_DEAL = 'Deal';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['card_pic_and_address_id', 'goods_type_id'], 'integer'],
            [['goods_type_id', 'issue_date'], 'required'],
            [['issue_date', 'validity', 'log'], 'safe'],
            [['status', 'remarks'], 'string'],
            [['reference_number'], 'string', 'max' => 255],
            ['status', 'in', 'range' => [
                    self::STATUS_DRAFT,
                    self::STATUS_DEAL,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'card_pic_and_address_id' => 'Card Pic And Address ID',
            'goods_type_id' => 'Goods Type ID',
            'issue_date' => 'Issue Date',
            'reference_number' => 'Reference Number',
            'status' => 'Status',
            'remarks' => 'Remarks',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'validity' => 'Validity',
            'log' => 'Log',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotationJobs()
    {
        return $this->hasMany(\app\models\QuotationJob::className(), ['quotation_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\QuotationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\QuotationQuery(get_called_class());
    }


    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_DRAFT => 'Draft',
            self::STATUS_DEAL => 'Deal',
        ];
    }

}
