<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "quotation_job_detail".
 *
 * @property integer $id
 * @property integer $quotation_job_id
 * @property string $name
 * @property integer $unit_of_measurement_id
 * @property integer $currency_id
 * @property string $value
 * @property integer $unit_of_measurement_id_2
 *
 * @property \app\models\QuotationJob $quotationJob
 * @property string $aliasModel
 */
abstract class QuotationJobDetail extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_job_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['quotation_job_id', 'unit_of_measurement_id', 'currency_id', 'unit_of_measurement_id_2'], 'integer'],
            [['name', 'unit_of_measurement_id', 'currency_id'], 'required'],
            [['value'], 'number'],
            [['name'], 'string', 'max' => 255],
            [['quotation_job_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\QuotationJob::className(), 'targetAttribute' => ['quotation_job_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'quotation_job_id' => 'Quotation Job ID',
            'name' => 'Name',
            'unit_of_measurement_id' => 'Unit Of Measurement ID',
            'currency_id' => 'Currency ID',
            'value' => 'Value',
            'unit_of_measurement_id_2' => 'Unit Of Measurement Id 2',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'unit_of_measurement_id' => 'uom',
            'currency_id' => 'currency',
            'unit_of_measurement_id_2' => 'uom_2',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotationJob()
    {
        return $this->hasOne(\app\models\QuotationJob::className(), ['id' => 'quotation_job_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\QuotationJobDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\QuotationJobDetailQuery(get_called_class());
    }


}
