<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "quotation_job".
 *
 * @property integer $id
 * @property integer $quotation_id
 * @property string $name
 *
 * @property \app\models\Quotation $quotation
 * @property \app\models\QuotationJobDetail[] $quotationJobDetails
 * @property string $aliasModel
 */
abstract class QuotationJob extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quotation_job';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['quotation_id'], 'integer'],
            [['name'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['quotation_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Quotation::className(), 'targetAttribute' => ['quotation_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'quotation_id' => 'Quotation ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotation()
    {
        return $this->hasOne(\app\models\Quotation::className(), ['id' => 'quotation_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuotationJobDetails()
    {
        return $this->hasMany(\app\models\QuotationJobDetail::className(), ['quotation_job_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\QuotationJobQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\QuotationJobQuery(get_called_class());
    }


}
