<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "session".
 *
 * @property string $id
 * @property integer $expire
 * @property resource $data
 * @property integer $user_id
 * @property integer $last_write
 * @property string $aliasModel
 */
abstract class Session extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'session';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id'], 'required'],
            [['expire', 'user_id', 'last_write'], 'integer'],
            [['data'], 'string'],
            [['id'], 'string', 'max' => 64],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'expire' => Yii::t('models', 'Expire'),
            'data' => Yii::t('models', 'Data'),
            'user_id' => Yii::t('models', 'User ID'),
            'last_write' => Yii::t('models', 'Last Write'),
        ];
    }



    /**
     * @inheritdoc
     * @return \app\models\activequery\SessionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\SessionQuery(get_called_class());
    }


}
