<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "status_perkawinan".
 *
 * @property integer $id
 * @property string $tipe
 * @property string $kode
 * @property string $nama
 * @property string $keterangan
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $created_by
 * @property string $updated_by
 *
 * @property \app\models\Karyawan[] $karyawans
 * @property string $aliasModel
 */
abstract class StatusPerkawinan extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const TIPE_TIDAK_KAWIN = 'TIDAK KAWIN';
    const TIPE_KAWIN = 'KAWIN';
    const TIPE_PTKP_DIGABUNG = 'PTKP Digabung';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'status_perkawinan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['tipe', 'keterangan'], 'string'],
            [['kode', 'nama'], 'required'],
            [['kode'], 'string', 'max' => 20],
            [['nama'], 'string', 'max' => 255],
            ['tipe', 'in', 'range' => [
                    self::TIPE_TIDAK_KAWIN,
                    self::TIPE_KAWIN,
                    self::TIPE_PTKP_DIGABUNG,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tipe' => 'Tipe',
            'kode' => 'Kode',
            'nama' => 'Nama',
            'keterangan' => 'Keterangan',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKaryawans()
    {
        return $this->hasMany(\app\models\Karyawan::className(), ['status_perkawinan_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\activequery\StatusPerkawinanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\activequery\StatusPerkawinanQuery(get_called_class());
    }


    /**
     * get column tipe enum value label
     * @param string $value
     * @return string
     */
    public static function getTipeValueLabel($value){
        $labels = self::optsTipe();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column tipe ENUM value labels
     * @return array
     */
    public static function optsTipe()
    {
        return [
            self::TIPE_TIDAK_KAWIN => 'Tidak Kawin',
            self::TIPE_KAWIN => 'Kawin',
            self::TIPE_PTKP_DIGABUNG => 'Ptkp Digabung',
        ];
    }

}
