<?php

namespace app\models;

use Yii;
use \app\models\base\KaryawanPtkp as BaseKaryawanPtkp;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "karyawan_ptkp".
 */
class KaryawanPtkp extends BaseKaryawanPtkp
{

    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                # custom behaviors
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
            parent::rules(),
            [
                # custom validation rules
            ]
        );
    }

    public function beforeSave($insert) {
        $this->tanggal_lahir = Yii::$app->formatter->asDate($this->tanggal_lahir, "php:Y-m-d");
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterFind() {
        $this->tanggal_lahir = Yii::$app->formatter->asDate($this->tanggal_lahir);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

}
